spring:
  profiles:
    active: dev


---

server:
  port: 7001
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka-dev

# C:\Windows\System32\drivers\etc\hosts  更改

#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com #eureska服务端的实例名称    ，如果这个名字一样，他会当作是同一个集群，导致集群失败，所以我还是改回来了，知道即可
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false #表示如果为false则表示自己为注册中心 "defaultZone", "http://localhost:8761/eureka/"
    service-url:  # 监控页面
      #单机：
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群（关联）
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      
 
---
server:
  port: 7001

spring:
  profiles: test
  application:
    name: springcloud-config-eureka-test

# C:\Windows\System32\drivers\etc\host  更改

#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称    ，如果这个名字一样，他会当作是同一个集群，导致集群失败，所以我还是改回来了，知道即可
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false #表示如果为false则表示自己为注册中心 "defaultZone", "http://localhost:8761/eureka/"
    service-url:  # 监控页面
      #单机： 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群（关联）
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
